version: '3'

services:
  app:
    container_name: "bucketful-app"
    image: ${BUCKETFUL_APP_IMAGE}
    ports:
      - "3030:3000"
    depends_on:
      - db
  db:
    container_name: "bucketful-db"
    image: "mongo:3.4"

